package warsgame

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Brick) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "X":
			z.X, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "Y":
			z.Y, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		case "W":
			z.W, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "W")
				return
			}
		case "H":
			z.H, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "H")
				return
			}
		case "D":
			z.D, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "D")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Brick) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "X"
	err = en.Append(0x85, 0xa1, 0x58)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.X)
	if err != nil {
		err = msgp.WrapError(err, "X")
		return
	}
	// write "Y"
	err = en.Append(0xa1, 0x59)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Y)
	if err != nil {
		err = msgp.WrapError(err, "Y")
		return
	}
	// write "W"
	err = en.Append(0xa1, 0x57)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.W)
	if err != nil {
		err = msgp.WrapError(err, "W")
		return
	}
	// write "H"
	err = en.Append(0xa1, 0x48)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.H)
	if err != nil {
		err = msgp.WrapError(err, "H")
		return
	}
	// write "D"
	err = en.Append(0xa1, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.D)
	if err != nil {
		err = msgp.WrapError(err, "D")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Brick) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "X"
	o = append(o, 0x85, 0xa1, 0x58)
	o = msgp.AppendFloat64(o, z.X)
	// string "Y"
	o = append(o, 0xa1, 0x59)
	o = msgp.AppendFloat64(o, z.Y)
	// string "W"
	o = append(o, 0xa1, 0x57)
	o = msgp.AppendFloat64(o, z.W)
	// string "H"
	o = append(o, 0xa1, 0x48)
	o = msgp.AppendFloat64(o, z.H)
	// string "D"
	o = append(o, 0xa1, 0x44)
	o = msgp.AppendString(o, z.D)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Brick) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "X":
			z.X, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "Y":
			z.Y, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		case "W":
			z.W, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "W")
				return
			}
		case "H":
			z.H, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "H")
				return
			}
		case "D":
			z.D, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "D")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Brick) Msgsize() (s int) {
	s = 1 + 2 + msgp.Float64Size + 2 + msgp.Float64Size + 2 + msgp.Float64Size + 2 + msgp.Float64Size + 2 + msgp.StringPrefixSize + len(z.D)
	return
}
