package warsgame

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Portal) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "x":
			z.X, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "y":
			z.Y, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Portal) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "x"
	err = en.Append(0x82, 0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.X)
	if err != nil {
		err = msgp.WrapError(err, "X")
		return
	}
	// write "y"
	err = en.Append(0xa1, 0x79)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Y)
	if err != nil {
		err = msgp.WrapError(err, "Y")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Portal) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "x"
	o = append(o, 0x82, 0xa1, 0x78)
	o = msgp.AppendFloat64(o, z.X)
	// string "y"
	o = append(o, 0xa1, 0x79)
	o = msgp.AppendFloat64(o, z.Y)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Portal) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "x":
			z.X, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "y":
			z.Y, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Portal) Msgsize() (s int) {
	s = 1 + 2 + msgp.Float64Size + 2 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PortalLink) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "p1":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "P1")
					return
				}
				z.P1 = nil
			} else {
				if z.P1 == nil {
					z.P1 = new(Portal)
				}
				var zb0002 uint32
				zb0002, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "P1")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "P1")
						return
					}
					switch msgp.UnsafeString(field) {
					case "x":
						z.P1.X, err = dc.ReadFloat64()
						if err != nil {
							err = msgp.WrapError(err, "P1", "X")
							return
						}
					case "y":
						z.P1.Y, err = dc.ReadFloat64()
						if err != nil {
							err = msgp.WrapError(err, "P1", "Y")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "P1")
							return
						}
					}
				}
			}
		case "p2":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "P2")
					return
				}
				z.P2 = nil
			} else {
				if z.P2 == nil {
					z.P2 = new(Portal)
				}
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "P2")
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "P2")
						return
					}
					switch msgp.UnsafeString(field) {
					case "x":
						z.P2.X, err = dc.ReadFloat64()
						if err != nil {
							err = msgp.WrapError(err, "P2", "X")
							return
						}
					case "y":
						z.P2.Y, err = dc.ReadFloat64()
						if err != nil {
							err = msgp.WrapError(err, "P2", "Y")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "P2")
							return
						}
					}
				}
			}
		case "LastUsed":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "LastUsed")
				return
			}
			if z.LastUsed == nil {
				z.LastUsed = make(map[string]int64, zb0004)
			} else if len(z.LastUsed) > 0 {
				for key := range z.LastUsed {
					delete(z.LastUsed, key)
				}
			}
			for zb0004 > 0 {
				zb0004--
				var za0001 string
				var za0002 int64
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LastUsed")
					return
				}
				za0002, err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "LastUsed", za0001)
					return
				}
				z.LastUsed[za0001] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PortalLink) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "p1"
	err = en.Append(0x83, 0xa2, 0x70, 0x31)
	if err != nil {
		return
	}
	if z.P1 == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 2
		// write "x"
		err = en.Append(0x82, 0xa1, 0x78)
		if err != nil {
			return
		}
		err = en.WriteFloat64(z.P1.X)
		if err != nil {
			err = msgp.WrapError(err, "P1", "X")
			return
		}
		// write "y"
		err = en.Append(0xa1, 0x79)
		if err != nil {
			return
		}
		err = en.WriteFloat64(z.P1.Y)
		if err != nil {
			err = msgp.WrapError(err, "P1", "Y")
			return
		}
	}
	// write "p2"
	err = en.Append(0xa2, 0x70, 0x32)
	if err != nil {
		return
	}
	if z.P2 == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 2
		// write "x"
		err = en.Append(0x82, 0xa1, 0x78)
		if err != nil {
			return
		}
		err = en.WriteFloat64(z.P2.X)
		if err != nil {
			err = msgp.WrapError(err, "P2", "X")
			return
		}
		// write "y"
		err = en.Append(0xa1, 0x79)
		if err != nil {
			return
		}
		err = en.WriteFloat64(z.P2.Y)
		if err != nil {
			err = msgp.WrapError(err, "P2", "Y")
			return
		}
	}
	// write "LastUsed"
	err = en.Append(0xa8, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.LastUsed)))
	if err != nil {
		err = msgp.WrapError(err, "LastUsed")
		return
	}
	for za0001, za0002 := range z.LastUsed {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "LastUsed")
			return
		}
		err = en.WriteInt64(za0002)
		if err != nil {
			err = msgp.WrapError(err, "LastUsed", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PortalLink) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "p1"
	o = append(o, 0x83, 0xa2, 0x70, 0x31)
	if z.P1 == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 2
		// string "x"
		o = append(o, 0x82, 0xa1, 0x78)
		o = msgp.AppendFloat64(o, z.P1.X)
		// string "y"
		o = append(o, 0xa1, 0x79)
		o = msgp.AppendFloat64(o, z.P1.Y)
	}
	// string "p2"
	o = append(o, 0xa2, 0x70, 0x32)
	if z.P2 == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 2
		// string "x"
		o = append(o, 0x82, 0xa1, 0x78)
		o = msgp.AppendFloat64(o, z.P2.X)
		// string "y"
		o = append(o, 0xa1, 0x79)
		o = msgp.AppendFloat64(o, z.P2.Y)
	}
	// string "LastUsed"
	o = append(o, 0xa8, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64)
	o = msgp.AppendMapHeader(o, uint32(len(z.LastUsed)))
	for za0001, za0002 := range z.LastUsed {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendInt64(o, za0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PortalLink) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "p1":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.P1 = nil
			} else {
				if z.P1 == nil {
					z.P1 = new(Portal)
				}
				var zb0002 uint32
				zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "P1")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "P1")
						return
					}
					switch msgp.UnsafeString(field) {
					case "x":
						z.P1.X, bts, err = msgp.ReadFloat64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "P1", "X")
							return
						}
					case "y":
						z.P1.Y, bts, err = msgp.ReadFloat64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "P1", "Y")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "P1")
							return
						}
					}
				}
			}
		case "p2":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.P2 = nil
			} else {
				if z.P2 == nil {
					z.P2 = new(Portal)
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "P2")
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "P2")
						return
					}
					switch msgp.UnsafeString(field) {
					case "x":
						z.P2.X, bts, err = msgp.ReadFloat64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "P2", "X")
							return
						}
					case "y":
						z.P2.Y, bts, err = msgp.ReadFloat64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "P2", "Y")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "P2")
							return
						}
					}
				}
			}
		case "LastUsed":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastUsed")
				return
			}
			if z.LastUsed == nil {
				z.LastUsed = make(map[string]int64, zb0004)
			} else if len(z.LastUsed) > 0 {
				for key := range z.LastUsed {
					delete(z.LastUsed, key)
				}
			}
			for zb0004 > 0 {
				var za0001 string
				var za0002 int64
				zb0004--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LastUsed")
					return
				}
				za0002, bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LastUsed", za0001)
					return
				}
				z.LastUsed[za0001] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PortalLink) Msgsize() (s int) {
	s = 1 + 3
	if z.P1 == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 2 + msgp.Float64Size + 2 + msgp.Float64Size
	}
	s += 3
	if z.P2 == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 2 + msgp.Float64Size + 2 + msgp.Float64Size
	}
	s += 9 + msgp.MapHeaderSize
	if z.LastUsed != nil {
		for za0001, za0002 := range z.LastUsed {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.Int64Size
		}
	}
	return
}
